# nixpacks.toml - Attempt 2

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["bun run build"]

# Use 'cmds' (list) for consistency, even with one command
[phases.start]
cmds = ["node server.js"]
