# nixpacks.toml

# Phase d'installation (déjà présente)
[phases.install]
cmds = ["npm install"]

# Phase de build (ajoutez ceci !)
# Exécute la commande pour construire le frontend dans le dossier ./dist
[phases.build]
cmds = ["bun run build"]

# Phase de démarrage (ajoutez ceci !)
# Définit comment lancer le serveur Node.js
[phases.start]
cmd = "node server.js"
